config/routes.rb
Rails.application.routes.draw do
  resources :users, only: %i[new create show]
  resources :invitations, only: %i[new create index destroy show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :events
  get '/sign_in', to: 'users#sign_in_view'
  post '/sign_in', to: 'users#sign_in'
  get '/sign_out', to: 'users#sign_out'
  get 'invitations/:id/accept', to: 'invitations#accept'
  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :invitations, class_name: 'Invitation', foreign_key: 'attended_event_id'
  has_many :attendees, through: :invitations, source: 'attendee'

  validates :date, presence: true

  scope :past, -> { where('date < ?', Time.now) }
  scope :upcoming, -> { where('date > ?', Time.now) }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, class_name: 'Event', foreign_key: 'creator_id'
  has_many :invitations, class_name: 'Invitation', foreign_key: 'attendee_id'
  has_many :accepted_invitations, -> { where(accepted: true) }, class_name: 'Invitation', foreign_key: 'attendee_id'
  has_many :unaccepted_invitations, -> { where(accepted: false) }, class_name: 'Invitation', foreign_key: 'attendee_id'

  has_many :attended_events, through: :accepted_invitations, source: 'attended_event'

  # has_many :accepted_events, class_name: 'Event', through: :accepted_invitations, source: 'attended_event'

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :email, presence: true, uniqueness: { case_sensitive: false }

  def upcoming_events
    returned_events = []
    attended_events.each do |event|
      returned_events << event if event.date > Time.now
    end
    returned_events
  end

  def previous_events
    returned_events = []
    attended_events.each do |event|
      returned_events << event if event.date < Time.now
    end
    returned_events
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @upcoming_events = Event.upcoming
    @prev_events = Event.past
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
  end

  def create
    begin
      @user = User.find(session[:user_id])
    rescue ActiveRecord::RecordNotFound
      @user = nil
    end

    if @user
      @event = @user.created_events.build(event_params)
      @user.save

      if @event.persisted?
        flash[:notice] = 'Event created successfully'
        redirect_to event_path(@event)
      else
        flash[:notice] = "Couldn't create event"
        render :new
      end
    else
      flash[:notice] = 'Please sign in to create an event'
      redirect_to sign_in_path
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :date)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def index
    if session[:user_id]
      @invitations = User.find(session[:user_id]).unaccepted_invitations
    else
      flash[:notice] = 'Please sign in to view invitations'
      redirect_to sign_in_path
    end
  end

  def accept
    @invitation = Invitation.find(params[:id])
    @invitation.accepted = true

    if @invitation.save
      flash[:success] = 'Invitation accepted'

    else
      flash[:error] = 'Something went wrong'
    end
    redirect_to events_path
  end

  def new
    redirect_to sign_in_path if session[:user_id].nil?
    @invitation = Invitation.new
  end

  def create
    @invitation = Invitation.new(invitation_params)

    if @invitation.save
      flash[:notice] = 'Invitation successfully created'
      redirect_to events_path
    else
      flash[:notice] = 'Failed to create invitation'
      render 'new'
    end
  end

  def destroy
    @invitation = Invitation.find(params[:id])
    flash[:notice] = if @invitation.destroy
                       'Invitation was declined.'
                     else
                       'Something went wrong'
                     end
    redirect_to invitations_path
  end

  private

  def invitation_params
    params.require(:invitation).permit(:id, :attendee_id, :attended_event_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @upcoming_events = @user.upcoming_events
    @prev_events = @user.previous_events
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        session[:logged_in_user_name] = @user.name
        format.html { redirect_to events_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }

      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def sign_in_view
    render :sign_in_view
  end

  def sign_in
    name = params[:name]
    @user = User.find_by(name: name)
    if @user
      session[:logged_in_user_name] = @user.name
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:notice] = 'Invalid user name'
      render :sign_in_view
    end
  end

  def sign_out
    session[:logged_in_user_name] = nil
    session[:user_id] = nil
    redirect_to events_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def events_by(user)
    Event.where(creator: user)
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
  def invitation_accept_path(invitation)
    "/invitations/#{invitation.id}/accept"
  end

  def invitation_message(invitation)
    'you have no invitations' if invitation.empty?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def all_other_users
    return [] if session[:user_id].nil?

    users = User.all
    filtered_users = []
    users.each do |u|
      filtered_users << u if u.id != session[:user_id]
    end
    filtered_users
  end

  def current_user
    session[:user_id].nil? ? nil : User.find(session[:user_id])
  end
end

app/views/events/index.html.erb
<h3 class="title">Upcoming events</h3>
<div class="row">
    <% @upcoming_events.each do |event| %>
    <div class="col-md-3">
        <div class="card">
            <%= image_tag("rss.jpg", :alt => "Card image cap", :class => "card-img-top" )  %>

            <div class="card-body">
                <h5 class="card-title"><%= event.title %> </h5>
                <p class="card-text"><%= event.description %> </p>
                <p class="card-text"><%= event.location %> </p>
                <p class="card-text"><%= event.date %> </p>

                <%= link_to "show event", event_path(event), class: "btn btn-primary " %>

            </div>
        </div>
    </div>
    <% end %>
</div>

<h3 class="title">Past events</h3>


<div class="row">
    <% @prev_events.each do |event| %>
    <div class="col-md-3">
        <div class="card">
            <%= image_tag("rss.jpg", :alt => "Card image cap", :class => "card-img-top" )  %>

            <div class="card-body">
                <h5 class="card-title"><%= event.title %> </h5>
                <p class="card-text"><%= event.description %> </p>
                <p class="card-text"><%= event.location %> </p>
                <p class="card-text"><%= event.date %> </p>

                <%= link_to "show event", event_path(event), class: "btn btn-primary" %>

            </div>
        </div>
    </div>
    <% end %>
</div>

<hr>
<%= link_to "new event", new_event_path, class: "btn btn-primary" %>

app/views/events/new.html.erb
<%= form_for @event do |f| %>
<%= f.label :title %>
<%= f.text_field :title %><br />
<%= f.label :description %>
<%= f.text_area :description %><br />
<%= f.label :date %>
<%= f.datetime_field :date %><br />

<%= f.submit :class => 'btn btn-primary pos' %>
<% end %>

app/views/events/show.html.erb
<h3 class="title">creator: <%= @event.creator.name %></h3>

<div class="row">
    <div class="col-md-6">
        <div class="card">
            <%= image_tag("rss.jpg", :alt => "Card image cap", :class => "card-img-top" )  %>

            <div class="card-body">
                <h5 class="card-title"><%= @event.title %> </h5>
                <p class="card-text"><%= @event.description %></p>
                <p class="card-text"><%= @event.location %> </p>
                <p class="card-text"><%= @event.date %> </p>

            </div>
        </div>
    </div>

    <div class="col-md-6">
        <h3 class="title"> Event attendees </h3>


        <% @event.attendees.each do |attendee| %>
        <p>
            <%= attendee.name %>
        </p>
        <% end %>
    </div>
</div>

app/views/invitations/index.html.erb
<div class="row">
 <div class = "jumbotron">
<h3> <%= invitation_message(@invitations) %> </h3>  <span> <%= link_to "new invite", new_invitation_path, class: "btn btn-primary" %> </span>
 </div>
</div>


<div class="row">
    <% @invitations.each do |invitation| %>
        <div class="col-12 col-md-4 invited">
            <p> You have been invited to <%= invitation.attended_event.title %>! </p>
            <br>
            <%= link_to  "Accept", invitation_accept_path(invitation), class: "btn btn-primary" %>
            <%= link_to  "Decline", invitation_path(invitation), method: :delete, class: "btn btn-primary" %>
           
        </div>
    <% end %>
</div>

app/views/invitations/new.html.erb
<%= form_for @invitation do |f| %>
<%= f.label :attendee %>
<%= f.collection_select :attendee_id, all_other_users, :id, :name %>
<%= f.label :attended_event %>
<%= f.collection_select :attended_event_id, events_by( User.find(session[:user_id]) ), :id, :title %>

<%= f.submit :class => 'btn btn-primary pos' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# === bootstrap cdn ==== %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="navbar-brand">
            <% if session[:logged_in_user_name] %>
            <%= link_to "Welcome #{session[:logged_in_user_name]}", user_path(User.find(session[:user_id])), class: "btn btn-primary" %> 
            <a href="/sign_out" class="btn btn-primary psn">Sign out</a>
            <% else %>
            <a href="/sign_in" class="btn btn-primary psn">Sign in</a>
            <a href="/users/new" class="btn btn-primary psn">Sign up</a>
            <% end %>

        </div>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">

                    <%= link_to "events", events_path, class: " btn btn-danger psn" %>

                </li>

                <li class="nav-item active">

                    <%= link_to "invitations", invitations_path, class: " btn btn-primary psn inivites_btn" %>

                </li>


            </ul>
        </div>
    </nav>

    <div class="container">
    <% if flash[:notice] %>
        <div class="alert alert-danger" role="alert"> <%= flash[:notice] %> </div>
    <% end %>
        <%= yield %>

    </div>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
<% if user.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
        <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<%= form.label :name %>
<%= form.text_field :name %><br />

<%= form.label :email %>
<%= form.email_field :email %><br />

<%= form.label :address %>
<%= form.text_field :address %><br />


<div class="actions">
    <%= form.submit :class => "btn btn-primary let_log"%>
</div>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1 class="title">New User</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
    <div class="col-md-4">
        <div class="card">

            <%= image_tag("man.jpg", :alt => "Card image cap", :class => "card-img-top" )  %>

            <div class="card-body">
                <p class="card-text">name: <%= @user.name %></p>
                <p class="card-text">email: <%= @user.email %> </p>
                <p class="card-text">address: <%= @user.address %></p>

            </div>
        </div>

    </div> <%# === .col-md-4 ====%>
    
</div><%# ===.row ====%>

<div class="row">
<div class="col-md-4">
        <h3 class="title">created events</h3>



        <% @user.created_events.each do |event| %>

        <div class="card">

            <%= image_tag("rss.jpg", :alt => "Card image cap", :class => "card-img-top" )  %>

            <div class="card-body">
                <h5 class="card-title"><%= event.title %> </h5>
                <p class="card-text"><%= event.description %></p>
                <p class="card-text"><%= event.location %> </p>
                <p class="card-text"><%= event.date %> </p>

            </div>
        </div>


        <% end %>
    </div>

    <div class="col-md-4">
        <h3 class="title">Upcoming events</h3>



        <% @upcoming_events.each do |event| %>

        <div class="card">

            <%= image_tag("rss.jpg", :alt => "Card image cap", :class => "card-img-top" )  %>

            <div class="card-body">
                <h5 class="card-title"><%= event.title %> </h5>
                <p class="card-text"><%= event.description %></p>
                <p class="card-text"><%= event.location %> </p>
                <p class="card-text"><%= event.date %> </p>

            </div>
        </div>

        <% end %>


    </div>


    <div class="col-md-4">
        <h3 class="title">Previous Events</h3>



        <% @prev_events.each do |event| %>

        <div class="card">

            <%= image_tag("rss.jpg", :alt => "Card image cap", :class => "card-img-top" )  %>

            <div class="card-body">
                <h5 class="card-title"><%= event.title %> </h5>
                <p class="card-text"><%= event.description %></p>
                <p class="card-text"><%= event.location %> </p>
                <p class="card-text"><%= event.date %> </p>

            </div>
        </div>

        <% end %>


    </div>

</div><%# ===.row ====%>

<%= link_to 'Back', events_path, class: 'btn btn-primary let_log'%>

app/views/users/sign_in_view.html.erb
<h1 class="title">Hi</h1>
<%= form_tag( '/sign_in', method: :post) do |f| %>
<%= label_tag (:name) %>
<%= text_field_tag (:name) %>
<%= submit_tag "Sign in", :class => "btn btn-primary let_log" %>
<% end %>